CREATE DATABASE dbweeb;
USE dbweeb;
DROP DATABASE dbweeb;
CREATE TABLE INFORMACOES_NUTRICIONAIS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
		quantidadeProteina DOUBLE,
		lactose BOOLEAN,
    valorEnergetico DOUBLE,
    carboidratos DOUBLE,
		sodio DOUBLE,
    fibraAlimentar DOUBLE,
    gorduraTrans DOUBLE,
    goduraSaturada DOUBLE,
    gordurasTotais DOUBLE,
		porcaoGramas DOUBLE
);

CREATE TABLE INFORMACOES_NUTRICIONAIS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
		quantidadeProteina DOUBLE,
		lactose BOOLEAN,
		lipidio DOUBLE,
		porcaoGramas DOUBLE
);

CREATE TABLE OPCAO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nomeComida VARCHAR(30),
    categoria VARCHAR(30)
);

CREATE TABLE INGREDIENTE(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_opcao INT,
    nome VARCHAR(50)
);

CREATE TABLE OPCOES_DIARIAS (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dataRefeicao DATE,
    diaDaSemana VARCHAR(25),
    turno VARCHAR(25)
);

CREATE TABLE CARDAPIO (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	dataInicial DATE,
	dataFinal DATE
);

CREATE TABLE TIPO_USUARIO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nivelAcesso INT,
    preçoCredito DOUBLE
);

CREATE TABLE EMAIL(
	usuario VARCHAR(100),
    servidor VARCHAR(100),
    extensao VARCHAR(100)
);

CREATE TABLE LOGIN(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
    usuario VARCHAR(100),
    senha VARCHAR(100)
);

CREATE TABLE USUARIO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255),
    codIdentificador LONG,
    email VARCHAR(255),
    creditos DOUBLE,
    login INT,
    tipoUsuario INT,
    FOREIGN KEY(login) REFERENCES LOGIN(ID) ON UPDATE CASCADE,
    FOREIGN KEY(tipoUsuario) REFERENCES TIPO_USUARIO(ID) ON UPDATE CASCADE
);

CREATE TABLE VENDA(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    vendedor INT,
    quantidadeCredito DOUBLE,
    dataVenda DATE,
    horario TIME,
    FOREIGN KEY(vendedor) REFERENCES USUARIO(ID) ON UPDATE CASCADE
);

CREATE TABLE PAGAMENTO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	precoTotal DOUBLE,
    venda INT,
    cliente INT,
    FOREIGN KEY(cliente) REFERENCES USUARIO(ID) ON UPDATE CASCADE,
    FOREIGN KEY(venda) REFERENCES venda(ID) ON UPDATE CASCADE
);

CREATE TABLE RELATORIO (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dataCriado DATE,
    horario TIME,
    gerador INT,
    FOREIGN KEY(gerador) REFERENCES USUARIO(ID) ON UPDATE CASCADE
);

CREATE TABLE INGREDIENTE_OPCAO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nomeIngrediente VARCHAR(100),
    ID_opcao INT,
    FOREIGN KEY(ID_opcao) REFERENCES OPCAO(ID) ON UPDATE CASCADE
);

CREATE TABLE OPCAO_OPCOES_DIARIAS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_opcao INT,
    ID_opcoesDiarias INT,
    FOREIGN KEY(ID_opcao) REFERENCES OPCAO(ID) ON UPDATE CASCADE,
    FOREIGN KEY(ID_opcoesDiarias) REFERENCES OPCOES_DIARIAS(ID) ON UPDATE CASCADE
);

CREATE TABLE OPCOES_DIARIAS_CARDAPIO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_opcoesDiarias INT,
    ID_cardapio INT,
    FOREIGN KEY(ID_opcoesDiarias) REFERENCES OPCOES_DIARIAS(ID) ON UPDATE CASCADE,
    FOREIGN KEY(ID_cardapio) REFERENCES CARDAPIO(ID) ON UPDATE CASCADE
);

CREATE TABLE RELATORIO_PAGAMENTO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_relatorio INT,
    ID_pagamento INT,
    FOREIGN KEY(ID_relatorio) REFERENCES RELATORIO(ID) ON UPDATE CASCADE,
    FOREIGN KEY(ID_pagamento) REFERENCES PAGAMENTO(ID) ON UPDATE CASCADE
);
ALTER TABLE RELATORIO DROP COLUMN pagamentos;



INSERT INTO INFORMACOES_NUTRICIONAIS VALUES(null,2 ,TRUE , 4, 5, 6, 7, 8, 9, 10, 11);
INSERT INTO INFORMACOES_NUTRICIONAIS VALUES(null,21 ,TRUE , 41, 51, 61, 71, 81, 91, 101, 111);
INSERT INTO OPCAO VALUES (NULL, "COMIDA1", "COMIDA");
INSERT INTO OPCAO VALUES (NULL, "COMIDA2", "COMIDA");
INSERT INTO OPCAO VALUES (NULL, "COMIDA3", "COMIDA");
INSERT INTO OPCAO VALUES (NULL, "COMIDA4", "COMIDA");
INSERT INTO OPCAO VALUES (NULL, "COMIDA5", "COMIDA");
INSERT INTO OPCAO VALUES (NULL, "COMIDA6", "COMIDA");
INSERT INTO OPCOES_DIARIAS VALUES(NULL, "2018-04-08", "DOMINGO", "NOITE");
INSERT INTO OPCOES_DIARIAS VALUES(NULL, "2018-04-09", "SEGUNDA", "MANHA");
INSERT INTO OPCOES_DIARIAS VALUES(NULL, "2018-04-10", "TERCA", "NOITE");
INSERT INTO OPCOES_DIARIAS VALUES(NULL, "2018-04-11", "QUARTA", "MANHA");
INSERT INTO OPCOES_DIARIAS VALUES(NULL, "2018-04-12", "QUINTA", "NOITE");
INSERT INTO CARDAPIO VALUES(NULL, "2018-04-08", "2018-04-12");

INSERT INTO OPCOES_DIARIAS_CARDAPIO VALUES(NULL, 1, 1);
INSERT INTO OPCOES_DIARIAS_CARDAPIO VALUES(NULL, 2, 1);
INSERT INTO OPCOES_DIARIAS_CARDAPIO VALUES(NULL, 3, 1);
INSERT INTO OPCOES_DIARIAS_CARDAPIO VALUES(NULL, 4, 1);
INSERT INTO OPCOES_DIARIAS_CARDAPIO VALUES(NULL, 5, 1);

INSERT INTO OPCAO_OPCOES_DIARIAS VALUES(NULL, 1, 1);
INSERT INTO OPCAO_OPCOES_DIARIAS VALUES(NULL, 2, 1);
INSERT INTO OPCAO_OPCOES_DIARIAS VALUES(NULL, 3, 1);
INSERT INTO OPCAO_OPCOES_DIARIAS VALUES(NULL, 4, 2);
INSERT INTO OPCAO_OPCOES_DIARIAS VALUES(NULL, 5, 2);
INSERT INTO OPCAO_OPCOES_DIARIAS VALUES(NULL, 6, 2);

INSERT INTO INGREDIENTE_OPCAO VALUES(NULL, "INGREDIENTE1", 1);
INSERT INTO INGREDIENTE_OPCAO VALUES(NULL, "INGREDIENTE2", 1);
INSERT INTO INGREDIENTE_OPCAO VALUES(NULL, "INGREDIENTE3", 1);
INSERT INTO INGREDIENTE_OPCAO VALUES(NULL, "INGREDIENTE4", 1);

SELECT * FROM INFORMACOES_NUTRICIONAIS;
SELECT * FROM CARDAPIO;
SELECT * FROM OPCOES_DIARIAS WHERE diaDaSemana = "SEGUNDA";
SELECT * FROM OPCOES_DIARIAS_CARDAPIO;
SELECT * FROM OPCAO_OPCOES_DIARIAS, OPCOES_DIARIAS, OPCAO WHERE diaDaSemana = "SEGUNDA" 
		AND OPCAO_OPCOES_DIARIAS.ID_opcoesDiarias = OPCOES_DIARIAS.ID 
        AND OPCAO.ID = OPCAO_OPCOES_DIARIAS.ID_opcao
        GROUP BY nomeComida ;

SELECT diaDaSemana as DS FROM OPCOES_DIARIAS_CARDAPIO,OPCOES_DIARIAS  WHERE ID_cardapio = 1 AND TURNO = "NOITE" GROUP BY diaDaSemana;
SELECT nomeIngrediente  FROM CARDAPIO, OPCOES_DIARIAS,OPCAO, OPCAO_OPCOES_DIARIAS,OPCOES_DIARIAS_CARDAPIO, INGREDIENTE_OPCAO
WHERE CARDAPIO.dataInicial = "2018-04-08" 
		AND CARDAPIO.dataFinal = "2018-04-12"
		AND OPCOES_DIARIAS.diaDaSemana = "DOMINGO" 
		AND OPCAO_OPCOES_DIARIAS.ID_opcoesDiarias = OPCOES_DIARIAS.ID 
        AND OPCAO.ID = OPCAO_OPCOES_DIARIAS.ID_opcao
        AND INGREDIENTE_OPCAO.ID_opcao = OPCAO.ID
		GROUP BY nomeIngrediente;

DELETE FROM CARDAPIO WHERE ID = 5;

SELECT * FROM PAGAMENTO;

SELECT * FROM INFORMACOES_NUTRICIONAIS;

SELECT * FROM VENDA;

SELECT * FROM INFORMACOES_NUTRICIONAIS WHERE ID = 4;

SELECT * FROM INFORMACOES_NUTRICIONAIS WHERE quantidadeProteina = 1 AND lactose = true AND  valorEnergetico = 4 AND carboidratos = 5 AND sodio = 6 AND fibraAlimentar = 7 AND gorduraTrans = 8 AND goduraSaturada = 9 AND gordurasTotais = 10 AND porcaoGramas = 11;

#PESQUISA DE INGREDIENTE DA COMIDA '?'.
SELECT INGREDIENTE_OPCAO.ID as ID, nomeIngrediente as Ingrediente, nomeComida as Comida
FROM INGREDIENTE_OPCAO, OPCAO WHERE OPCAO.nomeComida = "COMIDA2" AND OPCAO.ID = INGREDIENTE_OPCAO.ID_opcao GROUP BY INGREDIENTE_OPCAO.ID;


ALTER TABLE VENDA ADD COLUMN dataVenda Date;
UPDATE VENDA SET dataVenda ="2018-04-13" WHERE ID = 2;

SELECT * FROM LOGIN WHERE usuario = "aaa" ;

ALTER TABLE LOGIN MODIFY COLUMN ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE;

DROP TABLE LOGIN;
